aws_access_key: 
aws_secret_key: 
key_content: |
 -----BEGIN RSA PRIVATE KEY-----
 -----END RSA PRIVATE KEY-----
key_name: 
region: eu-west-1
instance_groups: sg-fa45db9e
instance_type: t2.nano
instance_image: ami-47a23a30
instance_username: ubuntu
instance_count: 100
host_per_instance: 1
instance_name: HostpoolInstance
instance_os: linux
hostpool_url: http://localhost:8080
SOURCE_INSTANCE: HostpoolFeeder_2dc73
