tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.automation.a4c.config.orch.pub
  template_version: 1.4.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - alien-base-types:1.4.0-SNAPSHOT
  - org.alien4cloud.automation.a4c.pub:1.4.0-SNAPSHOT
  - tosca-normative-types:1.0.0-ALIEN14

node_types:
  org.alien4cloud.automation.a4c.config.orch.pub.nodes.OrchestratorConfigurator:
    abstract: true
    description: |
      Configure an orchestrator for A4C
    derived_from: tosca.nodes.Root
    properties:
      name:
        type: string
        required: true
        default: CFYOrchestrator
      pluginId:
        type: string
        required: true
        default: alien-cloudify-4-orchestrator-premium
      pluginBean:
        type: string
        required: true
        default: cloudify-orchestrator
    attributes:
      orchestratorId: { get_operation_output: [ SELF, Standard, start, orchestratorId ] }
      alien_url: { get_operation_output: [ SELF, Standard, start, alien_url ] }
      alien_user: { get_operation_output: [ SELF, Standard, start, alien_user ] }
      alien_password: { get_operation_output: [ SELF, Standard, start, alien_password ] }
    capabilities:
      location_config:
        type: org.alien4cloud.automation.a4c.config.orch.pub.capabilities.OrchestratorConfigurator
        occurrences: [ 0, UNBOUNDED ]
    requirements:
      - alien:
          capability: org.alien4cloud.automation.a4c.pub.capabilities.A4cRestApi
          relationship: org.alien4cloud.automation.a4c.config.orch.pub.relationships.ConnectsToA4C
          occurrences: [1, 1]

  org.alien4cloud.automation.a4c.config.orch.pub.nodes.LocationConfigurator:
    abstract: true
    description: |
      Configure a location for an A4C orchestrator
    derived_from: tosca.nodes.Root
    properties:
      name:
        type: string
        required: true
        default: MyLocation
      type:
        type: string
        required: true
        default: byon
    attributes:
      locationId: { get_operation_output: [ SELF, Standard, create, locationId ] }
    requirements:
      - orchestrator:
          capability: org.alien4cloud.automation.a4c.config.orch.pub.capabilities.OrchestratorConfigurator
          relationship: org.alien4cloud.automation.a4c.config.orch.pub.relationships.LocationHostedOnOrchestrator
          occurrences: [1, 1]
    interfaces:
      Standard:
        create:
          # create the location
          inputs:
            ANSIBLE_VERBOSE: true
            PLAYBOOK_ENTRY: create_location.yml
            name: { get_property: [SELF, name] }
            type: { get_property: [SELF, type] }
            orchestratorId: { get_attribute: [HOST, orchestratorId] }
            alien_url: { get_attribute: [HOST, alien_url] }
            alien_user: { get_attribute: [HOST, alien_user] }
            alien_password: { get_attribute: [HOST, alien_password] }
          implementation: playbook/playbook.ansible

capability_types:
  org.alien4cloud.automation.a4c.config.orch.pub.capabilities.OrchestratorConfigurator:
    derived_from: tosca.capabilities.Container

relationship_types:
  org.alien4cloud.automation.a4c.config.orch.pub.relationships.ConnectsToA4C:
    derived_from: tosca.relationships.ConnectsTo
    valid_target_types: [ org.alien4cloud.automation.a4c.pub.capabilities.A4cRestApi ]
    interfaces:
      Configure:
        pre_configure_source:
          inputs:
            ANSIBLE_VERBOSE: true
            PLAYBOOK_ENTRY: connect_a4c.yml
            alien_user: { get_property: [TARGET, rest, user] }
            alien_password: { get_property: [TARGET, rest, password] }
            alien_url: { concat: [get_property: [TARGET, rest, protocol], "://", get_attribute: [TARGET, public_ip_address], ":", get_property: [TARGET, rest, port]] }
          implementation: playbook/playbook.ansible
  org.alien4cloud.automation.a4c.config.orch.pub.relationships.LocationHostedOnOrchestrator:
    derived_from: tosca.relationships.HostedOn
