---
- name: Create config file for ElasticSearch collector
  template:
    src: ElasticSearchCollector.conf.j2
    dest: /etc/ansible_diamond/collectors/ElasticSearchCollector.conf
    force: yes

- name: "Define /tmp/a4cPlaybookRegistry/{{ SOURCE_NODE }}/{{ SOURCE_INSTANCE }}/dashboards as destination to store dashboards"
  set_fact:
    dashboard_dir: "/tmp/a4cPlaybookRegistry/{{ SOURCE_NODE }}/{{ SOURCE_INSTANCE }}/dashboards"
- name: "Ensure directory {{ dashboard_dir }} exists"
  file:
    path: "{{ dashboard_dir }}"
    state: directory
- name: "Create grafana dashboard for ES in {{ dashboard_dir }}/{{ SOURCE_INSTANCE }}-ES.dashboard"
  template:
    src: dashboard.json.j2
    dest: "{{ dashboard_dir }}/{{ TARGET_INSTANCE }}-ES.dashboard"
    force: yes
