
- name: Install Nginx
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:

    - name: Install epel-release
      yum:
        name: epel-release
        state: latest
        update_cache: true

    - name: Install nginx
      yum:
        name: nginx
        state: latest
        update_cache: true

    - name: Authorize httpd to connect
      shell:
        cmd: setsebool httpd_can_network_connect on -P
