
- name: Start Consul
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:

    - name: Start consul service
      service:
        name: nginx
        state: started
        enabled: yes
