repositories:
  - type: maven
    name: "Nexus Private"
    pluginId: "alien-maven-repository-plugin"
    configuration:
      url: "https://fastconnect.org/maven/content/repositories/fastconnect"
      user: tonton
      password: ******
  - type: maven
    name: "Nexus Private (SNAPSHOT)"
    pluginId: "alien-maven-repository-plugin"
    configuration:
      url: "https://fastconnect.org/maven/content/repositories/fastconnect-snapshot"
      user: tonton
      password: ******
