---

- name: Create config file for RabbitMQ collector
  template:
    src: RabbitMQCollector.conf.j2
    dest: /etc/ansible_diamond/collectors/RabbitMQCollector.conf
    force: yes

- name: "Define /tmp/a4cPlaybookRegistry/{{ SOURCE_NODE }}/{{ SOURCE_INSTANCE }}/dashboards as destination to store dashboards"
  set_fact:
    dashboard_dir: "/tmp/a4cPlaybookRegistry/{{ SOURCE_NODE }}/{{ SOURCE_INSTANCE }}/dashboards"
- name: "Ensure directory {{ dashboard_dir }} exists"
  file:
    path: "{{ dashboard_dir }}"
    state: directory
- name: "Create grafana dashboard for RabbitMQ in {{ dashboard_dir }}/{{ TARGET_INSTANCE }}-RabbitMQ.dashboard"
  template:
    src: dashboard.json.j2
    dest: "{{ dashboard_dir }}/{{ TARGET_INSTANCE }}-RabbitMQ.dashboard"
    force: yes
