---
- name: Create config file for Jolokia collector
  template:
    src: CloudifyCollector.conf.j2
    dest: /etc/ansible_diamond/collectors/CloudifyCollector.conf
    force: yes

- name: "Define /tmp/a4cPlaybookRegistry/{{ SOURCE_NODE }}/{{ SOURCE_INSTANCE }}/dashboards as destination to store dashboards"
  set_fact:
    dashboard_dir: "/tmp/a4cPlaybookRegistry/{{ SOURCE_NODE }}/{{ SOURCE_INSTANCE }}/dashboards"
- name: "Ensure directory {{ dashboard_dir }} exists"
  file:
    path: "{{ dashboard_dir }}"
    state: directory
- name: "Create grafana dashboard for Cloudify in {{ dashboard_dir }}/{{ SOURCE_INSTANCE }}.dashboard"
  template:
    src: dashboard.json.j2
    dest: "{{ dashboard_dir }}/{{ TARGET_INSTANCE }}-Cloudify.dashboard"
    force: yes
