
- name: Create temporary folder
  tempfile:
    state: directory
  register: a4c_dist

- name: Download a4c
  get_url:
    url: "{{ ALIEN_DIST_URL }}"
    dest: "{{ a4c_dist.path }}/a4c-dist"
    mode: 0600

- name: Extract archive
  unarchive:
    src: "{{ a4c_dist.path }}/a4c-dist"
    dest: ~/
    copy: no

- name: Remove temporary folder
  file:
    path: "{{ a4c_dist.path }}"
    state: absent

- name: Install latest jdk 1.8
  yum:
    name: java-1.8.0-openjdk-headless.x86_64
    state: latest

- name: Start application A4C
  shell:
    chdir: ~/alien4cloud
    cmd: nohup ./alien4cloud.sh > alien_nohup.log 2>&1 & echo $! > alien.pid
