tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.automation.a4c.config.orch.aws_location
  template_version: 1.4.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - alien-base-types:1.4.0-SNAPSHOT
  - org.alien4cloud.automation.a4c.config.orch.pub:1.4.0-SNAPSHOT
  - org.alien4cloud.automation.cloudify.hostpool.pub:1.4.0-SNAPSHOT
  - org.alien4cloud.automation.cloudify.manager.pub:1.4.0-SNAPSHOT
  - org.alien4cloud.automation.a4c.config.orch.cfy:1.4.0-SNAPSHOT
  - tosca-normative-types:1.0.0-ALIEN14

node_types:

  org.alien4cloud.automation.a4c.config.orch.aws_location.nodes.AWSLocationConfigurator:
    description: |
      Configure a AWS location for A4C
    derived_from: org.alien4cloud.automation.a4c.config.orch.pub.nodes.LocationConfigurator
    properties:
      type:
        type: string
        required: true
        default: byon
        constraints:
          - valid_values: [ "amazon" ]
    interfaces:
      Standard:
        start:
          # create the location on demand resources
          inputs:
            ANSIBLE_VERBOSE: true
            PLAYBOOK_ENTRY: create_byon_location_resource.yml
            orchestratorId: { get_attribute: [HOST, orchestratorId] }
            locationId: { get_attribute: [SELF, locationId] }
            alien_url: { get_attribute: [HOST, alien_url] }
            alien_user: { get_attribute: [HOST, alien_user] }
            alien_password: { get_attribute: [HOST, alien_password] }
          implementation: scripts/configure_aws_location_resources.sh
