tosca_definitions_version: alien_dsl_2_0_0

metadata:
  template_name: org.alien4cloud.doc.kube.topology.09-simple-ubuntu-configmap
  template_version: 2.1.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - org.alien4cloud.doc.kube.ConfigContainer:2.1.0-SNAPSHOT
  - docker-types:2.1.0-SNAPSHOT

topology_template:
  node_templates:
    Container:
      type: org.alien4cloud.extended.container.types.ContainerRuntime
    Ubuntu:
      type: artemis.ais.containers.nodes.Ubuntu
      properties:
        cpu_share: 1.0
        mem_share: "128 MB"
      requirements:
        - hostedOnContainerRuntimeContainerHost:
            type_requirement: host
            node: Container
            capability: org.alien4cloud.extended.container.capabilities.ApplicationHost
            relationship: org.alien4cloud.extended.container.relationships.HostedOnContainerRuntime
