tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.automation.a4c.config.setup
  template_version: 1.4.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - alien-base-types:1.4.0-SNAPSHOT
  - org.alien4cloud.automation.a4c.pub:1.4.0-SNAPSHOT
  - tosca-normative-types:1.0.0-ALIEN14

node_types:
  org.alien4cloud.automation.a4c.config.setup.nodes.Configurator:
    derived_from: org.alien4cloud.automation.a4c.pub.nodes.AlienConfigurator
    description: |
      Set up A4C with a given config.
    tags:
      icon: /images/git.png
    properties:
      repositoryUrl:
        type: string
        required: true
        default: https://github.com/alien4cloud/tosca-normative-types.git
    interfaces:
      Standard:
        create:
          description: Setup A4C.
          # create the location
          inputs:
            ANSIBLE_VERBOSE: true
            PLAYBOOK_ENTRY: start.yml
          implementation: playbook/playbook.ansible
        delete:
          descsription: Clear all config.
