---

- name: pip psycopg2
  pip: name=psycopg2 
  
- name: Create config file for Postgresql collector
  template: src=PostgresqlCollector.conf.j2 dest=/etc/ansible_diamond/collectors/PostgresqlCollector.conf force=yes

