tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.automation.a4c.config.repository
  template_version: 2.2.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - alien-base-types:3.0.0-SNAPSHOT
  - tosca-normative-types:1.0.0-ALIEN20
  - org.alien4cloud.automation.a4c.pub:2.2.0-SNAPSHOT

node_types:
  org.alien4cloud.automation.a4c.config.repository.nodes.ArtifactRepositoriesConfigurator:
    description: |
      Configure artifact repositories from a resources file.
    derived_from: org.alien4cloud.automation.a4c.pub.nodes.AlienConfigurator
    artifacts:
      - resources_file_artifact:
          type: tosca.artifacts.File
    interfaces:
      Standard:
        start:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: create_repositories.yml
            alien_user: { get_property: [HOST, rest, user] }
            alien_password: { get_property: [HOST, rest, password] }
            alien_url: { get_attribute: [HOST, alien_url] }
          implementation: playbook/playbook.ansible
