tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.automation.a4c.config.offline_plugin
  template_version: 1.4.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - tosca-normative-types:1.0.0-ALIEN14
  - org.alien4cloud.www.apache.pub:1.4.0-SNAPSHOT

node_types:

  org.alien4cloud.automation.a4c.config.offline_plugin.nodes.PluginConfigurator:
    derived_from: org.alien4cloud.www.apache.pub.nodes.WebApplication
    description: >
      The TOSCA Apache Node Type represents an apache component
      that can be managed and run by a TOSCA Compute Node Type.
    interfaces:
      Standard:
        create:
          inputs:
            document_root: { get_property: [HOST, document_root] }
            ip_address: { get_property: [HOST, data_endpoint, ip_address] }
            port: { get_property: [HOST, data_endpoint, port] }
          implementation: scripts/create.sh
