
services:
  - nodeType: "org.alien4cloud.monitoring.pub.nodes.GraphiteService"
    nodeTypeVersion: "1.4.0-SNAPSHOT"
    name: GraphiteAsAService
    version: "1.4.0-SNAPSHOT"
    # TODO: setup security for all locations
    nodeInstance:
      attributeValues:
        # we use a list here because "state: started" must be the last operation
        - capabilities.data_endpoint.protocol: http
        - capabilities.data_endpoint.ip_address: 172.31.15.18
        - capabilities.data_endpoint.port: 2003
        - state: started

  - nodeType: "org.alien4cloud.monitoring.pub.nodes.GrafanaService"
    nodeTypeVersion: "1.4.0-SNAPSHOT"
    name: GrafanaAsAService
    version: "1.4.0-SNAPSHOT"
    # TODO: setup security for all locations
    nodeInstance:
      attributeValues:
        # we use a list here because "state: started" must be the last operation
        - capabilities.http_endpoint.ip_address: 172.31.15.18
        - capabilities.http_endpoint.port: 3000
        - capabilities.http_endpoint.user: admin
        - capabilities.http_endpoint.password: admin
        - state: started

  - nodeType: "org.alien4cloud.automation.cloudify.manager.pub.nodes.CloudifyManagerService"
    nodeTypeVersion: "1.4.0-SNAPSHOT"
    name: Cloudify4ManagerAsAService
    version: "1.4.0-SNAPSHOT"
    # TODO: setup security for all locations
    nodeInstance:
      attributeValues:
        # we use a list here because "state: started" must be the last operation
        - capabilities.cloudify_api_v3.protocol: https
        - capabilities.cloudify_api_v3.ip_address: 172.31.41.251
        - capabilities.cloudify_api_v3.port: 443
        - capabilities.cloudify_api_v3.admin_username: admin
        - capabilities.cloudify_api_v3.admin_password: admin
        - state: started
