- name: pip httplib2
  pip: name=httplib2 
  #pip: name=httplib2 extra_args="--user"

- name: Provision EC2 instances
  ec2:
     aws_access_key: "{{ aws_access_key }}"
     aws_secret_key: "{{ aws_secret_key }}"
     key_name: "{{ key_name }}"
     region: "{{ region }}"
     group_id: "{{ instance_groups }}"
     instance_type: "{{ instance_type }}"
     image: "{{ instance_image }}"
     wait: true
     exact_count: "{{ instance_count }}"
     count_tag:
        Name: "{{ instance_name }}"
     instance_tags:
        Name: "{{ instance_name }}_{{ SOURCE_INSTANCE }}"
        HostpoolFeeder: "{{ SOURCE_INSTANCE }}" 
  register: ec2

- name: Add instances to hostpool
  uri: 
    url: "{{ hostpool_url }}/hosts"
    method: POST
    return_content: yes
    body: 
      hosts:
        - endpoint:
            ip: "{{ item.private_ip }}"
            protocol: "ssh"
            port: 22
          name: "{{ item.private_ip }}"
          credentials:
            username: "{{ instance_username }}"
            key: "{{ key_content }}"
          os: "{{ instance_os }}"
    body_format: json
    status_code: 201  
  with_items: ec2.instances
