
- name: Install ansible
  yum:
    name: ansible
    state: latest

- name: Create temporary folder
  tempfile:
    state: directory
  register: temp_dir

- name: Download Yorc
  shell:
    chdir: ~/alien4cloud
    cmd: "curl -L {{ YORC_DIST_URL }} -o {{ temp_dir.path }}/yorc_dist"

- name: Creates yorc directory
  file:
    path: ~/yorc
    state: directory

- name: Extract archive
  unarchive:
    src: "{{ temp_dir.path }}/yorc_dist"
    dest: ~/yorc
    copy: no

- name: Remove temporary folder
  file:
    path: "{{ temp_dir.path }}"
    state: absent

- name: Configure Yorc
  template:
    src: config.yorc.json.j2
    dest: ~/yorc/config.yorc.json
    force: yes

- name: Start Yorc
  shell:
    chdir: ~/yorc
    cmd: nohup ./yorc server > yorc.log 2>&1 & echo $! > yorc.pid
